prod:
  type: postgres
  host: localhost
  user: postgres
  password: 123456
  dbname: postgres
  schema: dbtl_bookshop
test:
  type: postgres
  host: localhost
  user: localuser
  password: my_password
  port: 5432
  dbname: bookshop
  schema: dbtl_bookshop
